# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: continuity 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "continuity"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bob Potter"]
  s.date = "2013-09-24"
  s.description = "Distributed scheduling of jobs"
  s.email = "bobby.potter@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "continuity.gemspec",
    "examples/worker.rb",
    "lib/continuity.rb",
    "lib/continuity/cron_entry.rb",
    "lib/continuity/periodic_entry.rb",
    "lib/continuity/redis_backend.rb",
    "lib/continuity/scheduler.rb",
    "lib/continuity/zk_backend.rb",
    "spec/spec_helper.rb",
    "spec/zk_backend_spec.rb",
    "test/helper.rb",
    "test/redis.conf",
    "test/test_cron_entry.rb",
    "test/test_periodic_entry.rb",
    "test/test_race_issues.rb",
    "test/test_redis_backend.rb",
    "test/test_scheduler.rb",
    "test/test_zk_integration.rb"
  ]
  s.homepage = "http://github.com/bpot/continuity"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.4"
  s.summary = "Allows you to distribute job scheduling across a number of processes"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<redis>, [">= 0"])
      s.add_development_dependency(%q<zk>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<zk>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.3.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<zk>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.3.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

